name: bump-npm-version

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  bump:
    name: Bump version
    if: "!contains( github.ref, 'release' )"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Get version
      id: get_version
      run: |
        version=$(echo "$GITHUB_HEAD_REF" | sed -e "s/^release\///")
        echo "version=$version" >> "$GITHUB_OUTPUT"
    - name: Update npm version
      run: npm version ${{ steps.get_version.outputs.version }} --git-tag-version=false --allow-same-version
    - name: Commit changes
      uses: EndBug/add-and-commit@v10
      with:
        default_author: github_actions
        message: Bump version to ${{ steps.get_version.outputs.version }}
        add: package.json package-lock.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
